Swtpg consolidation developments
DUNE-DAQ/readoutlibs pull request #101
Opened 2023-03-23 17:09 UTC by adam-abed-abud

Resolves #100

2023-03-24 10:46 UTC, gcrone approved these changes
Looks OK to me

2023-03-27 21:06 UTC, roland-sipos requested changes
Remove possibly accidental LOG messages.

2023-03-27 21:06 UTC, roland-sipos commented on include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx
> +          TLOG() << "Charlie: The delay on this FAILED readout requests is: " << delay << " and the request timeout is: " << m_request_timeout_ms;
Please ommit using of first names in debug messages.... 
Also, what does this delay calulcates?? If this is an important metric, it should be added to opmon, not as a log.

2023-03-27 21:06 UTC, roland-sipos commented on include/readoutlibs/models/detail/ReadoutModel.hxx
> +  //TLOG_DEBUG(TLVL_QUEUE_POP) << "Received DataRequest"
Spurious TLOG comment?

2023-03-28 06:19 UTC, roland-sipos commented on include/readoutlibs/models/detail/ReadoutModel.hxx
> +  //TLOG_DEBUG(TLVL_QUEUE_POP) << "Received DataRequest"
Also, this will spam logs!

2023-03-29 12:49 UTC, roland-sipos commented
@glehmannmiotto can you please have a look on this? It has clashing changes with the request handling functiond.

2023-03-29 13:03 UTC, roland-sipos commented
I would propose to close this PR, and open a fresh one just with the changes on the schema for the config and the info.

2023-03-30 09:10 UTC, roland-sipos commented
Closing PR, as schema changes went in with another one.

2023-03-30 09:10 UTC, closed without merging