Added plane TPG threshold configurables.
DUNE-DAQ/readoutlibs pull request #169
Opened 2024-05-07 11:37 UTC by aeoranday

Configurables PR for TPG threshold by plane implementation in [fdreadoutlibs](https://github.com/DUNE-DAQ/fdreadoutlibs/pull/177). The `<plane>_threshold` default value of 0 makes that plane's threshold the same as `tpg_threshold` during runtime.

2024-05-08 12:48 UTC, alessandrothea requested changes

2024-05-08 12:48 UTC, alessandrothea commented on schema/readoutlibs/readoutconfig.jsonnet
> +            s.field("collection_threshold", self.count, 0,
`tpg_collection_threshold` maybe

2024-05-08 12:48 UTC, alessandrothea commented on schema/readoutlibs/readoutconfig.jsonnet
> +            s.field("induction1_threshold", self.count, 0,
`tpg_induction1_threshold`

2024-05-08 12:48 UTC, alessandrothea commented on schema/readoutlibs/readoutconfig.jsonnet
> +            s.field("induction2_threshold", self.count, 0,
`tpg_induction2_threshold`

2024-05-08 12:48 UTC, alessandrothea commented on schema/readoutlibs/readoutconfig.jsonnet
>              s.field("tpg_threshold", self.count, 120,
What is this used for? Remove?

2024-05-08 12:54 UTC, aeoranday commented on schema/readoutlibs/readoutconfig.jsonnet
>              s.field("tpg_threshold", self.count, 120,
Plane thresholds that were not explicitly set default to `tpg_threshold` and keeps some backwards compatibility. It is easy enough to remove.

2024-05-09 09:04 UTC, aeoranday commented
Latest commit made the word choice changes to match what is used in `detchannelmaps`. Configs and variables now refer to planes 0, 1, and 2 instead of induction 1, induction 2, and collection.

2024-05-13 13:33 UTC, alessandrothea approved these changes

2024-05-14 16:35 UTC, merged